version: '3.8'
services:
  # PostgreSQL 15
  postgres15:
    container_name: postgres15
    image: "postgres:${POSTGRES_VERSION}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - vehicles-net
networks:
  vehicles-net:
    name: vehicles-net
    driver: bridge
